url: https://datacgn.github.io
baseurl: 

# Site settings
title: datacgn
email: pomogajko@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary:  3385ff
  secondary: 668cff  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Univ.-Prof. Dr. Jens Harbecke
  pic: jens
  position: Professor for Theoretical Philosophy 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Kirill Pomogajko
  pic: kirill
  position: Full Stack Data Scientist
  social:
    - title: twitter
      url: https://twitter.de/pomogajko
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/pomogajko
  - title: linkedin
    url: https://www.linkedin.com/in/k

# Postal address (add as many lines as necessary)
address:
  - line: Thessaloniki-Allee 19
  - line: 51103 Köln

# Build settings
markdown: kramdown
permalink: pretty
